feat: ready for first review
VlaPol/TMS_Lesson_25 pull request #1
Opened 2023-04-08 15:30 UTC by VlaPol

2023-04-09 19:45 UTC, oleg-grigorijan requested changes

2023-04-09 19:45 UTC, oleg-grigorijan commented on src/Main.java
> +        final String FILMS_FILE_NAME = "D:\\Work\\Programming\\@TMS\\TMS_Lesson_25\\TV_Show\\films.csv";
Захардкоженые абсолютные пути – это зло. Этот код просто не отработает на другой машине, где нет такой структуры директорий. Этот код невозможно будет завести на Linux/macOS в принципе. Хотя бы относительный путь от рабочей директории уже будет лучше

2023-04-09 19:45 UTC, oleg-grigorijan commented on src/Main.java
> +        final String FILMS_FILE_NAME = "D:\\Work\\Programming\\@TMS\\TMS_Lesson_25\\TV_Show\\films.csv";
Знать пути к этим файлам – это ответственность конкретного репозитория, а не этого клиентского кода

2023-04-09 19:45 UTC, oleg-grigorijan commented on src/by/tms/repository/TVShowRepository.java
> +    List<? extends Show> getDataFromFile(Path path) throws IOException;
Wildcard не рекомендуется использовать как возвращаемый тип данных:
https://stackoverflow.com/a/22815270

Он может быть удобен в параметрах и локальных переменных, но в возвращаемом типе он только создаст сложности на вызывающей стороне без никаких преимуществ

2023-04-09 19:45 UTC, oleg-grigorijan commented on src/by/tms/repository/TVShowRepositoryImpl.java
> +    }
По заданию требовалось, чтобы этот метод возвращал List<Show>, который содержит все фильмы из файла и все сериалы из другого файла вместе. Параметра тут не будет

2023-04-15 10:42 UTC, oleg-grigorijan requested changes

2023-04-15 10:42 UTC, oleg-grigorijan commented on src/by/tms/repository/TVShowRepositoryImpl.java
> +        BufferedReader br = new BufferedReader(new FileReader(path.toString()));
try-with-resources

2023-04-15 10:42 UTC, oleg-grigorijan commented on src/by/tms/repository/TVShowRepositoryImpl.java
> +        BufferedReader br = new BufferedReader(new FileReader(path.toString()));
try-with-resources

2023-04-15 10:42 UTC, oleg-grigorijan commented on src/by/tms/repository/TVShowRepository.java
> +    List<Show> getDataFromFile() throws IOException;
В данном случае мы раскрываем детали внутренней реализации, когда делаем throws IOException. Мы прямо в абстракции говорим, что реализации будут осуществлять ввод-вывод. Но потенциально у нас может быть in-memory хранение в какой-нибудь коллекции. Потенциально мы можем работать с базой данных, а там будет SQLException, который не расширяет IOException. 
Если ты прям хочешь здесь checked исключение, то лучший вариант – создать свой тип а-ля RepositoryException, в который оборачивать другие исключения (например, IOException). Можно организовать целую иерархию RepositoryException, если нам нужно отделять какие-то специфические случаи.
По факту самый простой и популярный вариант – обернуть внутри реализации IOException в unchecked исключение а-ля UncheckedIOException и перевыбросить

2023-04-15 10:42 UTC, oleg-grigorijan commented on src/by/tms/repository/TVShowRepositoryImpl.java
> +    final Path FILMS_FILE_NAME = Path.of("films.csv");
private static final

2023-04-15 10:42 UTC, oleg-grigorijan commented on src/by/tms/models/Show.java
> +        this.ratesCounter = ratesCounter;
По-хорошему бы ещё провалидировать некоторые атрибуты на здравый смысл. Например, количество тут не может быть отрицательным

2023-04-18 19:18 UTC, VlaPol commented on src/by/tms/repository/TVShowRepository.java
> +    List<Show> getDataFromFile() throws IOException;
Исправил

2023-04-18 19:18 UTC, VlaPol commented on src/by/tms/repository/TVShowRepositoryImpl.java
> +        BufferedReader br = new BufferedReader(new FileReader(path.toString()));
Исправил

2023-04-18 19:18 UTC, VlaPol commented on src/by/tms/repository/TVShowRepositoryImpl.java
> +        BufferedReader br = new BufferedReader(new FileReader(path.toString()));
Исправил

2023-04-18 19:19 UTC, VlaPol commented on src/by/tms/repository/TVShowRepositoryImpl.java
> +    final Path FILMS_FILE_NAME = Path.of("films.csv");
упустил, исправил

2023-04-26 15:36 UTC, merged